# Generated by Django 3.2.16 on 2023-01-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleId', models.CharField(max_length=50)),
                ('roleName', models.CharField(max_length=50)),
            ],
        ),
    ]
