# Generated by Django 3.2.16 on 2023-01-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
