# Generated by Django 3.2.16 on 2023-01-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerId',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
