# Generated by Django 3.2.16 on 2022-12-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nrOfTimedOrdered',
            field=models.IntegerField(default=0),
        ),
    ]
