# Generated by Django 3.2.16 on 2022-12-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20221229_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='parentId',
            new_name='parent_id',
        ),
    ]
